// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTVRmx2i2OOcWxC-DnuynHN6KWysXM3uE',
    appId: '1:951231117988:web:e59f661c43e31772fcc431',
    messagingSenderId: '951231117988',
    projectId: 'experience-app-56e09',
    authDomain: 'experience-app-56e09.firebaseapp.com',
    storageBucket: 'experience-app-56e09.firebasestorage.app',
    measurementId: 'G-5QVK03582Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjuSOw3ayG-nt83ymh2fdekXJPZLeVuM',
    appId: '1:951231117988:android:568fc2f4be942cc7fcc431',
    messagingSenderId: '951231117988',
    projectId: 'experience-app-56e09',
    storageBucket: 'experience-app-56e09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjv_X3bXQzuEEENldWOOWbIyRMpnayMS8',
    appId: '1:951231117988:ios:ad60a4da57cfc159fcc431',
    messagingSenderId: '951231117988',
    projectId: 'experience-app-56e09',
    storageBucket: 'experience-app-56e09.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjv_X3bXQzuEEENldWOOWbIyRMpnayMS8',
    appId: '1:951231117988:ios:ad60a4da57cfc159fcc431',
    messagingSenderId: '951231117988',
    projectId: 'experience-app-56e09',
    storageBucket: 'experience-app-56e09.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTVRmx2i2OOcWxC-DnuynHN6KWysXM3uE',
    appId: '1:951231117988:web:02a96f13816907a3fcc431',
    messagingSenderId: '951231117988',
    projectId: 'experience-app-56e09',
    authDomain: 'experience-app-56e09.firebaseapp.com',
    storageBucket: 'experience-app-56e09.firebasestorage.app',
    measurementId: 'G-R2YKMTWFHN',
  );
}
